[package]
name = "bezier_edit"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
num = "0.4.3"
nalgebra = "0.33.2"
bevy_mod_openxr = "0.3.0"
bevy_mod_xr = "0.3.0"
bevy_xr_utils = "0.3.0"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[features]
vr_enable = []
