[package]
name = "bezier_edit"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0", default-features = true }
num = "0.4.3"
nalgebra = "0.33.2"
bevy_mod_openxr = "0.3.0"
bevy_mod_xr = "0.3.0"
bevy_xr_utils = "0.3.0"
openxr = "0.19.0"
variantly = "0.4.0"
bevy_lunex = "0.4.1"
rayon = "1.10.0"
struct-patch-derive = "0.10.3"
struct-patch = "0.10.3"
serde = "1.0.219"
serde_json = "1.0.140"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[features]
vr_enable = []
